name: flutter_project_test
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.1
  url_launcher: ^6.2.5
  http: ^1.2.0
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  shared_preferences: ^2.2.2
  webview_flutter: ^4.4.0
  webview_flutter_android: ^4.4.2
  intl: ^0.18.1
  mime: ^1.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/banner.png
    - assets/logo.png
    - assets/Jasa cuci sepatu promosi 1.png
    - assets/Jasa cuci sepatu promosi 1 (1).png
    - assets/Jasa cuci sepatu promosi 1 (2).png
    - assets/Jasa cuci sepatu promosi 1 (3).png
    - assets/Jasa cuci sepatu promosi 1 (4).png
    - assets/Jasa cuci sepatu promosi 1 (5).png
    - assets/Jasa cuci sepatu promosi 1 (6).png
    - assets/Jasa cuci sepatu promosi 1 (7).png
    - assets/Jasa cuci sepatu promosi 1 (8).png
    - assets/Jasa cuci sepatu promosi 1 (9).png
